### ISSUE TITLE
Registration image issue

### ISSUE THREAD

**Issue by dmseaton** [damanager/HallamInternetTest#1]
Some test users don't have registration images in their user meta. Please fix.

**Comment by isaiahoke** [comment]
@dmseaton Alright thats fine. I shall fix it asap and comment here

**Comment by isaiahoke** [comment]
Hello @dmseaton its working on my end.  This script below does the function also I will be attaching screenshot 


<img width="1440" alt="Screenshot 2019-07-17 at 00 51 29" src="https://user-images.githubusercontent.com/8944439/61337397-10c74400-a82d-11e9-983b-53bd38cebe05.png">

images shown are 

- https://via.placeholder.com/600/4b0323

- https://via.placeholder.com/600/61b17c


`//function.php file from hallam
//HallamInternet 
//<? php declare( strict_types=1 ); // there seems to be an error on this due to 
/**
 * Adds a random image to user upon registration.
 *
 * @param int $user_id
 */
function tt_user_register( int $user_id ): void {

	$photo_id = rand( 1, 10000 );

	$curl = curl_init();
	curl_setopt_array( $curl, [
		CURLOPT_RETURNTRANSFER => 1,
		CURLOPT_URL            => 'https://jsonplaceholder.typicode.com/photos/' . $photo_id,
		CURLOPT_HTTPHEADER => [ 'content-type: application/json'],  //We need to content typoe header set for receiving JSON response.
	] );
	$response = curl_exec( $curl );
	curl_close( $curl );

	$data = json_decode( $response );

	update_user_meta( $user_id, 'register_image', $data->url );
}


//add_action( 'tt_user_logged_in', 'tt_user_register', 10, 1 ); // The action hook should be 'user_register'

add_action( 'user_register', 'tt_user_register', 10, 1 );`

**Comment by dmseaton** [comment]
From a sample set of 100 users:

![Screenshot from 2019-07-17 10-33-15](https://user-images.githubusercontent.com/8384343/61364748-58c28700-a87e-11e9-865b-3d3c1e36e868.png)

**Comment by isaiahoke** [comment]
hello @dmseaton 

I have run a sample test of 100 users and attached the screenshots.

I have also test the url to find out the max ID that is allowed and reduced this to 5000. 

Not sure I have figured out all bugs but I am trying to make this challenge work as this is interesting.

Any tips or bugs left to do ?


<img width="603" alt="Screenshot 2019-07-19 at 12 36 48" src="https://user-images.githubusercontent.com/8944439/61532521-eee2e280-aa21-11e9-8ce9-e4302771660d.png">
<img width="534" alt="Screenshot 2019-07-19 at 12 36 58" src="https://user-images.githubusercontent.com/8944439/61532522-ef7b7900-aa21-11e9-82ec-330e5fa65463.png">


<img width="1054" alt="Screenshot 2019-07-19 at 12 33 48" src="https://user-images.githubusercontent.com/8944439/61532415-a4616600-aa21-11e9-9916-ec3740993253.png">
<img width="1126" alt="Screenshot 2019-07-19 at 12 34 00" src="https://user-images.githubusercontent.com/8944439/61532416-a4616600-aa21-11e9-9f80-9ecc8528328d.png">

**Comment by dmseaton** [comment]
This has resolved the problem for new users.

**Comment by isaiahoke** [comment]
lol finally thats great to hear.

Thanks
